### ISSUE TITLE
downlload is not happening 

### ISSUE THREAD

**Issue by PURUSHOTHAM-REDDY-N** [moham96/dtorrent_task#1] opened 2023-09-18 10:41 UTC
hi @moham96 

im trying to use torrent downloading plugin d_torrent_task but im unable to download the file 

this is my code https://github.com/PURUSHOTHAM-REDDY-N/Flutter-video-player/blob/master/lib/src/pages/downloads_page.dart

please check it once and this is my log

![image](https://github.com/moham96/dtorrent_task/assets/84611950/9309f10f-26a4-4ef1-8180-25820a41feaf)

please help me with this.

**Comment by PURUSHOTHAM-REDDY-N** [comment] 2023-09-20 06:35
@moham96  i will be  waiting for you update thank you 😃 .

**Comment by moham96** [comment] 2023-09-22 07:00
@PURUSHOTHAM-REDDY-N could you try the `dev` branch and see if it's working for you

**Comment by PURUSHOTHAM-REDDY-N** [comment] 2023-09-22 09:37
@moham96    is there any way that i can download torrents using magnetlinks , im searching all over internet about this thing but i didnt got any lead . if you know can you guide me  please

**Comment by moham96** [comment] 2023-09-22 09:51
@PURUSHOTHAM-REDDY-N yes, see the example in https://github.com/moham96/dtorrent_task/blob/dev/example/metadata_example.dart

**Comment by PURUSHOTHAM-REDDY-N** [comment] 2023-09-23 04:59
@moham96  HI , for magnet link also it is coming as previous download is not happening 
SEE 
![image](https://github.com/moham96/dtorrent_task/assets/84611950/0af4974a-46fa-4368-804e-3e86388bdda5)

i used the dev branch this time

**Comment by PURUSHOTHAM-REDDY-N** [comment] 2023-09-23 05:40
is it working in your android device

**Comment by moham96** [comment] 2023-09-23 08:07
Well to be honest all my tests were done on MacOS
From the errors you'r posting it seems like 'reusePort' is not supported on android,
You can remove that option and try again to see if it's possible, you might need to comment out the lines that start the LSD service as well,
Again i will be solving these issues and start testing on android and other platform when i have the time

**Comment by PURUSHOTHAM-REDDY-N** [comment] 2023-09-23 08:56
i tried it but no use .
![image](https://github.com/moham96/dtorrent_task/assets/84611950/7c95f327-8fcc-4f06-991a-62fdfd9b2a8c)

please resolve this when you are free , im ready to pay you for this if you want.

**Comment by PURUSHOTHAM-REDDY-N** [comment] 2023-09-23 13:05
see this fork https://github.com/xhns/torrent_task     it is working with torrent file but magnet link feature is not implemented

**Comment by moham96** [comment] 2023-10-01 17:44
> see this fork https://github.com/xhns/torrent_task it is working with torrent file but magnet link feature is not implemented

Well I had some time to test it and metadata download works fine on the dev branch, it is slow due to the nature of BitTorrent DHT (which I might be able to optimize when I have the time), you might want to speed it up by discovering peers from trackers along with DHT, see this code here:

https://github.com/moham96/dtorrent_task/blob/2ea9ea685a8fcfe5c4059106d60baf2bedda73b6/example/metadata_example.dart#L67C1-L78

**Comment by PURUSHOTHAM-REDDY-N** [comment] 2023-10-02 03:03
HI @moham96

i tested with dev branch still it is not working and im not getting any errors .

**Comment by wengxianxun** [comment] 2024-04-09 15:01
so , this bug is fix now?

**Comment by moham96** [comment] 2024-04-09 17:58
> so , this bug is fix now?

The library can download fine with very good speed, it can also download metadata but you'll have to bootstrap the `MetadataDownloader` with peers from trackers and not rely on DHT(since DHT is broken due to moham96/bittorrent_dht#1

if you have a minimal reproducible code for a download that is not working please post it here


also use the `optimization` branch when testing

**Comment by wengxianxun** [comment] 2024-04-09 23:38
I only see downloading through torrent, or is there a way to convert magnet links to torrent first?

**Comment by wengxianxun** [comment] 2024-04-09 23:40
> MetadataDownloader

can you upload one demo code ? thank you .

**Comment by moham96** [comment] 2024-04-10 05:27
> > MetadataDownloader
> 
> can you upload one demo code ? thank you .

There is already an example in the repo https://github.com/moham96/dtorrent_task/blob/main/example/metadata_example.dart

**Comment by moham96** [comment] 2024-04-12 18:44
I will close this issue, feel free to re-open

**Closed** 2024-04-12 18:45 UTC
